### PR TITLE
Phase out Crouton.java for AppMsg.java

### PR DESCRIPTION
**Pull request by ghost**
When building this application from source code, library dependencies reference a non-existent Crouton.java file which has since been removed from the library AppMsg and merged into AppMsg.java. I believe it is beneficial to replace references of Crouton and replace them with AppMsg for an easier build.

### CODE REVIEW

**Comment by adneal** [comment]
Hey, thanks for the pull request! We usually don't push changes into this repo, we work from the CM fork. 

We've actually already made this change over there. Also, if you'd like to contribute more to Apollo or any other apps in CM, you'll need to submit them through Gerrit for code review before hand.

https://github.com/CyanogenMod/android_packages_apps_Apollo
http://review.cyanogenmod.org/

**Comment by ghost** [comment]
@adneal Gotcha! Sorry for the goof. Also, is the issue tracker located at the Gerrit code review site as well?

**Comment by ocdtrekkie** [comment]
@adneal F-Droid builds off this repo. You might want to let them know you use a different one now.

Does the "CM fork" work on a non-CM device?

**Comment by adneal** [comment]
@Feral2k We use JIRA for that. https://jira.cyanogenmod.org/

@ocdtrekkie We've always used the other, but I suppose I could toss them an email. And yes.

**Pull request closed without merging**
